url: https://nhtstudio.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: nht studio
email: nguyenhaitruonghp@gmail.com
description: "Photography"

# Team names, titles and social links
people:
- name: Nguyen Hai Truong
  pic: 1
  position: Lead photographer
  social:
    - title: twitter
      url: https://twitter.com/truongnh92
    - title: facebook
      url: https://facebook.com/haitruong.bkhn
    - title: linkedin
      url: https://www.linkedin.com/in/nguyen-hai-truong-hp/

- name: Nguyen Hai Dang
  pic: 2
  position: Lead Adobe Premiere / Lightroom
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/haidanghp02
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/truongnh92
  - title: facebook
    url: https://facebook.com/nhtstudio92
  - title: flickr
    url: https://www.flickr.com/photos/nhtstudio
  - title: github
    url: https://github.com/nhtstudio

# Postal address (add as many lines as necessary)
address:
  - line: Keangnam Landmark Tower, Pham Hung street, Hanoi
  - line: 173 Luong Khanh Thien street, Truong Son town, An Lao Dist., Haiphong

# Build settings
markdown: kramdown
permalink: pretty
